# SAM CLI configuration file

version = 0.1

[default.deploy.parameters]
stack_name = "agentcore-feishu-notifier"
resolve_s3 = true
s3_prefix = "agentcore-feishu-notifier"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=dev"

[default.build.parameters]
use_container = false

[default.local_invoke.parameters]
env_vars = "env.json"
